import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import { ConvexClientProvider } from "@/custom-hooks/ConvexClientProvider";
import "./globals.css";
import Header from "@/_header/Header";
import SecondtothelastPart from "@/secondtothelastPart/secondtothelastPart";
import LastPartofLandingPage from "@/lastpartodLanding/lastPartofLandingPage";
import Footer from "@/_footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased lg:w-[1440px] md:w-full w-[768px] `}
      >
        <ConvexClientProvider>
          <Header />
          {children}
          <div className="mb-[100px]">
            <SecondtothelastPart />
          </div>
          <LastPartofLandingPage />
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
